version: "3.2"
services:
  php:
    build:
      context: .
    image: webuxmotion/framework:1.0.0
    networks:
      - frontend
      - backend
    environment:
      - MYSQL_HOST=framework-mysql-app
      - MYSQL_USER=frameworkuser
      - MYSQL_PASSWORD=frameworkpass
      - MYSQL_DB=framework_db
    volumes:
      - ./:/var/www/html/
    ports:
      - "60001:80"
    container_name: framework-php-app
  mysql:
    image: mysql:5.7
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=frameworkuser
      - MYSQL_PASSWORD=frameworkpass
      - MYSQL_DATABASE=framework_db
    container_name: framework-mysql-app
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - "60002:80"
    environment:
      - PMA_HOST=framework-mysql-app
      - PMA_PORT= 3306
    volumes:
      - /sessions
    container_name: framework-phpmyadmin-app
networks:
  frontend:
  backend:
